- name: Run kafka using a project directory
  hosts: all
  gather_facts: no
  tasks:
    - set_fact: 
        remote_compose_dir=/tmp/ansible-docker-service
        local_compose_dir=kafka
    - file: 
        path: "{{ remote_compose_dir }}"
        state: directory
    - name: Upload docker-compose files
      synchronize: 
        src: "{{ local_compose_dir }}"
        dest: "{{ remote_compose_dir }}"

    - name: Create and start services
      docker_compose:
        project_src: "{{ remote_compose_dir }}/{{ local_compose_dir }}"
      register: output

    - debug:
        var: output